---
title: Arizona Aquifer Recharge Suitability Analysis
author:
  - name: Travis Zalesky
    orcid: 0009-0006-0181-3099
    corresponding: true
    email: travisz@arizona.edu
    roles:
      - Author
      - GIST Software and Applications
      - Cartography
      - Suitability Analysis
    affiliations: University of Arizona
keywords:
  - Arizona Tri University Recharge (ATUR)
  - water table
  - ground water
abstract: |
  Aquifer recharge can be either passive or active, and is implemented in a variety of ways. This analysis seeks to identify regions across AZ which are boadly suitable for aquifer recharge projects as a general template for more focuse analysis.
plain-language-summary: |
  Identifying regions in AZ where surface water can be stored long-term as ground water.
key-points:
  #| TBD
date: last-modified
bibliography: references.bib
#| citation:
  #| container-title: Earth and Space Science
number-sections: true
jupyter: python3
---

## Introduction

## Data & Methods {#sec-data-methods}
### Elevation
#### DEM
Elevation and elevation derivatives from 30-m NASA SRTM. USGS 3-DEM (10m) product not suitable for full study area analysis due to (1) the large area of missing data in Mexico, and (2), the excessively high spatial resolution (massively increasing computational requirements).

SRTM elevation sinks filled prior to calculating slope and aspect.

**Should elevation be directly used in the suitability analysis?**

#### Slope
Slope derived from hydrologically conditioned (filled) 30-m SRTM layer using quadratic surface function and a fixed 30-m neighborhood. Slope measured in °.

> Higher slopes are less suitable because thinning is both more expensive and more precipitation will end up as runoff.

Slope classified from 1-10 using a continuous function in ArcPro Suitability Mapper.

#### Aspect
Aspect calculated as with slope. Aspect reference point at N. Pole.

> Aspect has a large impact on solar radiation.
> Closer to 0 or 360 is desired, low suitability scores for closeness.

Aspect classified from 1-10 using a continuous function in ArcPro Suitability Mapper.

### Precipitation
**Data source?**

* **PRISM normals**
  + 800m resolution
  + All months (30-Y)
* **Custom PRISM**
  + 1Km resolution
  + Subset months of interest
  + Custom date range
  + Custom averaging function
  + More granular control over data

**Also applies to Temp and other Climactic variables of interest.**



## Conclusion {#sec-conclusions}

## References {.unnumbered}
